repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    # Detects *your* aws credentials from the aws cli credentials file, 
    # this needs to be set before used. ref: https://pre-commit.com/hooks.html
    # -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-json
    -   id: check-yaml